# Report Model Performance Metrics


This notebook illustrate how to generate performance report from model results saved in output/prediction folder.

In [35]:
import pandas as pd
import sys
sys.path.append('../src')

import perf_eval as v

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [36]:
# Show performance of the Full model results saved into {model_path}

result_path = 'prediction/200/0/Full_EBM'
#result_path = 'prediction/200/0/ProtoNER_EBM'
#result_path = 'prediction/200/0/Full_minus_JL_EBM'
#result_path = 'prediction/200/0/Full_minus_attention_EBM'
classify_perf, tag_perf = v.report_performance(result_path)

In [37]:
# classification performance
classify_perf

# average across labels
classify_perf.mean(axis=0)

                  p_3     r_3    f1_3  sent_prc
label
interventions  0.8095  0.8784  0.8425    0.8493
outcomes       0.7469  0.7348  0.7408    0.7906
participants   0.8692  0.7855  0.8252    0.8363

p_3         0.8085
r_3         0.7995
f1_3        0.8029
sent_prc    0.8254
dtype: float64

In [38]:
# tagging performance
tag_perf

# average across labels
tag_perf.mean(axis = 0)

,token_p_3,token_r_3,token_f1_3,bert_pre_3,bert_rec_3,bert_f1_3,prc
label,,,,,,,
interventions,0.5688,0.8132,0.6694,0.7395,0.8505,0.7912,0.7656
outcomes,0.6002,0.6263,0.6130,0.7092,0.6729,0.6906,0.6764
participants,0.8049,0.7019,0.7499,0.8663,0.7765,0.8189,0.8040

token_p_3     0.6580
token_r_3     0.7138
token_f1_3    0.6774
bert_pre_3    0.7717
bert_rec_3    0.7667
bert_f1_3     0.7669
prc           0.7487
dtype: float64